#!/usr/bin/env python
# -*- coding: utf-8 -*-
#############################################
#                                           #
#          Com -> Gen converter             #
#              S.Nenon 2012                 #
#                                           #
#############################################

import os
import os.path
import sys
from dftb.comClass import *


##################################################################################################################################################
# Aide 
help='''\n\n==Help==
Syntax:
  com2gen [filein] [fileout]
  com2gen *

Converts filein in fileout
[filein]    must be a .com file. 
[fileout]   optional: specify the .gen outfile name. Default: <filein>.gen (<filein>_001.gen if it already exists)
*           will convert all .com files in current folder
\n'''

########################### parse args
nArgs = len(sys.argv)
filelist = []
if nArgs < 2: # no args case
  sys.exit('Error in arguments syntax.\n'+help)

elif nArgs == 2:# 1 arg
  if sys.argv[1][-4:] != '.com' or not os.path.exists(sys.argv[1]):
    sys.exit('Input file ('+sys.argv[1]+') must be a valid .com file in the current folder.\n'+help)
  else:
    filein = sys.argv[1]
    cpt = 1
    fileout = sys.argv[1][:-4]+'.gen'
    while os.path.exists(fileout):
      fileout = sys.argv[1][:-4]+'_'+("%d"%cpt).zfill(3)+'.gen'
      cpt += 1
    filelist.append([filein,fileout])
elif nArgs == 3: # 2 args
  if sys.argv[1][-4:] != '.com' or not os.path.exists(sys.argv[1]):
    sys.exit('Input file ('+sys.argv[1]+') must be a valid .com file in the current folder.\n'+help)
  if sys.argv[2][-4:] != '.gen':
    answer = ''
    while answer != 'y' and answer != 'n':
      answer = raw_input('Output file ('+sys.argv[2]+') should be a .gen file. Proceed? (y/n)\n')
    if answer == 'n':
      sys.exit('retry with another name')
    else:
      fileout = sys.argv[2]
      filestart,filext = fileout.split('.')
      cpt = 1
      while os.path.exists(fileout):
        fileout = filestart+'_'+("%d"%cpt).zfill(3)+'.'+filext
        cpt += 1
  filein = sys.argv[1]
  filelist.append([filein,fileout])

elif nArgs > 3: # case with *
  for i in sys.argv[1:]:
    if '.com' in i:
      filein = i
      fileout = filein.split('.')[0]+'.gen'
      filestart,filext = fileout.split('.')
      cpt = 1
      while os.path.exists(fileout):
        fileout = filestart+'_'+("%d"%cpt).zfill(3)+'.'+filext
        cpt += 1
      filelist.append([filein,fileout])

if len(filelist) == 0:
  sys.exit('Nothing to convert...'+help)
  
########################### main
for filein,fileout in filelist:
  print('Conversion of %s in %s'%(filein,fileout))
  try:
    comFile(filein).writeGen(fileout)
    print('Done\n')
  except:
    print('Error......\n')
print('==== Finished! ====')

















