#!/usr/bin/env python
# -*- coding: utf-8 -*-
#############################################
#                                           #
#            pbcmodif                       #
#              S.Nenon 2013                 #
#                                           #
#############################################

from dftb.geometry import isPtInCell
import numpy as np
from random import randint


pts=[]
with open('detpts','w') as ptsfile:
	for i in range(20000):
		pts.append([0.001*randint(-9999,9999),0.001*randint(-9999,9999)])
		ptsfile.write(' '.join([str(x) for x in pts[-1]])+'\n')

vec=[]
with open('detvec','w') as vecfile:
	for i in range(2):
		vec.append([0.001*randint(-4444,4444),0.001*randint(-4444,4444)])
		vecfile.write('0.0 0.0 '+' '.join([str(x) for x in vec[i]])+'\n')
	vecfile.write(' '.join([str(x) for x in vec[1]])+' '+' '.join([str(x) for x in vec[0]])+'\n')
	vecfile.write(' '.join([str(x) for x in vec[0]])+' '+' '.join([str(x) for x in vec[1]])+'\n')

with open('detout','w') as outfile:
	for i in pts:
		if isPtInCell(i,vec[0],vec[1]):
			outfile.write(' '.join([str(x) for x in i])+'\n')

with open('detgnu','w') as gnufile:
	gnufile.write('set term x11\n p "detpts" w p,"detvec" w vectors,"detout" w p')

