#!/usr/bin/env python
# -*- coding: utf-8 -*-
#############################################
#                                           #
#               Gen Viewer                  #
#              S.Nenon 2012                 #
#                                           #
#############################################

import os
import os.path
import sys
from dftb.genClass import *
import numpy as np
from mpl_toolkits.mplot3d import Axes3D,axes3d
import matplotlib.pyplot as plt

colordic = {'B':'yellow','C':'grey','H':'white','N':'blue','O': 'red','S':'yellow','Zn':'black','Si':'lightgrey','Ti':'black'}

# parse args
if len(sys.argv) != 2 or not '.gen' in sys.argv[1]:
  sys.exit('Error.\n Usage: genView file.gen')

# get geom
gf = genFile(sys.argv[1])

nat = gf.n_atoms
geom = gf.geometry # [ [1, 'atom1', x1, y1, z1] , ... , [N, 'atomN', xN, yN, zN] ]
atoms = gf.atom_names


fig = plt.figure()
ax = Axes3D(fig)
ax.set_axis_off()

for at in atoms:
  xs = []
  ys = []
  zs = []
  maxx = 0.
  maxy = 0.
  maxz = 0.
  minx = 9999999999.
  miny = 9999999999.
  minz = 9999999999.
  for i in geom:
    maxx = max(maxx,i[2])
    minx = min(minx,i[2])
    maxy = max(maxy,i[3])
    miny = min(miny,i[3])
    maxz = max(maxz,i[4])
    minz = min(minz,i[4])

xsize = maxx-minx
ysize = maxy-miny
zsize = maxz-minz
maxsize = max(xsize,ysize,zsize)
minx = minx - (maxsize-xsize)/2.
miny = miny - (maxsize-ysize)/2.
minz = minz - (maxsize-zsize)/2.
maxx = maxx + (maxsize-xsize)/2.
maxy = maxy + (maxsize-ysize)/2.
maxz = maxz + (maxsize-zsize)/2.
at_radius = maxsize/0.2

for at in atoms:
  xs = []
  ys = []
  zs = []
  for i in geom:
    if i[1] == at:
      xs.append(i[2])
      ys.append(i[3])
      zs.append(i[4])
  ax.scatter(xs, ys, zs, c=colordic[at], s=at_radius, marker='o',alpha=1.0)


ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_xlim3d(minx,maxx)
ax.set_ylim3d(miny,maxy)
ax.set_zlim3d(minz,maxz)


plt.show()














