#!/usr/bin/env python
# -*- coding: utf-8 -*-
#############################################
#                                           #
#            geo2bary                       #
#              S.Nenon 2012                 #
#                                           #
#############################################

from dftb.genClass import genFile
import sys,os.path

help="""
set the barycenter to be at (0,0,0).

Syntax:
  geo2bary in.gen 

"""


# parse args ==============================================================
if len(sys.argv) != 2:
  sys.exit('Incorrect argument number\n'+help)

# filename
if not '.gen' in sys.argv[1] or not os.path.exists(sys.argv[1]):
  sys.exit('First argument should be a .gen file in current folder\n'+help)
else:
  filein = sys.argv[1]

# main ==============================================================

gF = genFile(filein)
gF.geo2bary()
gF.savegen('saved.gen')

