#!/usr/bin/env python
# -*- coding: utf-8 -*-
#############################################
#                                           #
#            geo2center                     #
#              S.Nenon 2012                 #
#                                           #
#############################################

from dftb.genClass import genFile
import sys,os.path

help="""
set the barycenter to be at the center of the cell.

Syntax:
  geo2center in.gen 

"""


# parse args ==============================================================
if len(sys.argv) != 2:
  sys.exit('Incorrect argument number\n'+help)

# filename
if not '.gen' in sys.argv[1] or not os.path.exists(sys.argv[1]):
  sys.exit('First argument should be a .gen file in current folder\n'+help)
else:
  filein = sys.argv[1]

# main ==============================================================

gF = genFile(filein)

# coordinates of the cell's center
x = 0.0
y = 0.0
z = 0.0
for i in gF.lattice:
    x += i[0]/2.
    y += i[1]/2.
    z += i[2]/2.
center = [x,y,z]

# set the barycenter to be centered
gF.geo2bary()
gF.trans(center)

#save
gF.savegen('saved.gen')

